("a" ((ctgy . det)))
("an" ((ctgy . det)))
("ant" ((ctgy . n)))
("animal" ((ctgy . n)))
("bat" ((ctgy . n)))
("be" ((ctgy . v)))
("believe" ((ctgy . v)(prop-att . t)))
("Bill" ((ctgy . npr)(gen . m)))
("car" ((ctgy . n)))
("Carol" ((ctgy . npr)(gen . f)))
("cat" ((ctgy . n)))
("dog" ((ctgy . n)))
("elk" ((ctgy . n)))
("fox" ((ctgy . n)))
("girl" ((ctgy . n)))
("gnu" ((ctgy . n)))
("Guatemalan" ((ctgy . adj)))
("he" ((ctgy . pron)))
("Hector" ((ctgy . npr)(gen . m)))
("hen" ((ctgy . n)))
("is" ((ctgy . v)(root . "be")(num . sing)(tense . pres)))
("it" ((ctgy . pron)))
("John" ((ctgy . npr)(gen . m)))
("Lucy" ((ctgy . npr)(gen . f)))
("man" ((ctgy . n)(plur . "men")))
("Mary" ((ctgy .  npr)(gen . f)))
("men" ((ctgy . n)(root . "man")(num . plur)))
("mortal" ((ctgy . adj)))
("old" ((ctgy . adj)))
("owl" ((ctgy . n)))
("pear" ((ctgy . n)))
("pet" ((ctgy . n)))
("people" ((ctgy . n)(root . "person")(num . plur)))
("person" ((ctgy . n)(plur . "people")))
("philosophical" ((ctgy . adj)))
("pick" ((ctgy . v)))
("poor" ((ctgy . adj)))
("rat" ((ctgy . n)))
("rich" ((ctgy . adj)))
("saw" ((ctgy . n)(root . "saw1"))
       ((ctgy . v)(root . "see")(tense . past)))
("saw1" ((ctgy . n)(root . "saw")))
("see" ((ctgy . v)(past . "saw")(pastp . "seen")))
("seen" ((ctgy . v)(root . "see")(tense . pastp)(pprt . t)))
("she" ((ctgy . pron)))
("smart" ((ctgy . adj)))
("Socrates" ((ctgy . npr)(gen . m)))
("sow" ((ctgy . n)))
("Stu" ((ctgy . npr)(gen . m)))
("sweet" ((ctgy . adj)))
("tall" ((ctgy . adj)))
("that" ((ctgy . conj)))
("the" ((ctgy . det)))
("the-editor-of-Byte" ((ctgy . npr)(gen m f)))
("this" ((ctgy . demon)))
("what" ((ctgy . pron)))
("was" ((ctgy . v)(root . "be")(num . sing)(tense . past)))
("who" ((ctgy . pron)))
("wise" ((ctgy . adj)))
("yak" ((ctgy . n)))
("young" ((ctgy . adj)))

