
("a" ((ctgy . det)))
("an" ((ctgy . det)))
("animal" ((ctgy . n)))
("are" ((ctgy . v)(root . "be")(num . (sing plur))(tense . pres))
       ((ctgy . aux)(root . "be")(num . (sing plur))(tense . pres)))
("ball" ((ctgy . n)))
("be" ((ctgy . v)(root . "be")(presp . "being"))
      ((ctgy . aux) (root . "be")(presp . "being")))
("big" ((ctgy . adj)))
("boy" ((ctgy . n) (gen . m)(num . sing)))
("circus" ((ctgy . multi-start)(multi-rest . ("elephant"))))
("circus elephant" ((ctgy . n)))
("is" ((ctgy . v)(root . "be")(num . sing)(tense . pres))
      ((ctgy . aux)(root . "be")(num . sing)(tense . pres)))
("block" ((ctgy . n))
         ((ctgy . v)))
("can" ((ctgy . aux)(modal . t)(num . (sing plur)))
       ((ctgy . n)))
("catch" ((ctgy . v)(past . "caught")))
("caught" ((ctgy . v)(root . catch)(tense . past)))
("costume" ((ctgy . n)))
("clothes" ((ctgy . n)))
("dish" ((ctgy . n)))
("do" ((ctgy . v))
      ((ctgy . aux)))
("did" ((ctgy . aux)(root . "do")(tense . past))
       ((ctgy . v)(root . "do")(tense . past)))
("elephant" ((ctgy . n)))
("fish" ((ctgy . n)(num . (sing plur))))
("frog" ((ctgy . n)))
("gentleman" ((ctgy . n)))
("green" ((ctgy . adj)))
("he" ((ctgy . pro)))
("head" ((ctgy . n)))
("help" ((ctgy . n))
        ((ctgy . v)))
("I" ((ctgy . pro)))
("Jack" ((ctgy . npr)))
("love" ((ctgy . v)(stative . t)))
("move" ((ctgy . v)))
("performer" ((ctgy . n)))
("play" ((ctgy . v)(root . "play"))
        ((ctgy . n)(num . sing)))
("she" ((ctgy . pro)))
("story" ((ctgy . n)))
("take" ((ctgy . v)))
("tell" ((ctgy . v)(past . "told")))
("the" ((ctgy . det)))
("told" ((ctgy . v)(root . "tell")(tense . past)))
("will" ((ctgy . aux)(modal . t)(num . (sing plur))))
("you" ((ctgy . pro)))
("." ((ctgy . final-punc)))
