("a" ((ctgy . det) (num . sing))) 
("abase" ((ctgy . v)))
("abash" ((ctgy . v)))
("abate" ((ctgy . v)))
("abdicate" ((ctgy . v)))
("abet" ((ctgy . v)))
("abeyance" ((ctgy . n)))
("abhenry" ((ctgy . n)))
("abhorrent" ((ctgy . adj)))
("abject" ((ctgy . adj)))
("abort" ((ctgy . v)))
("abridge" ((ctgy . v)))
("absorb" ((ctgy . v)))
("abstain" ((ctgy . v)))
("abstinence" ((ctgy . n)))
("abundance" ((ctgy . adj)))
("abundant" ((ctgy . adj)))
("abyss"((cty . n)))
("accent" ((ctgy . n)))
("access" ((ctgy . n)))
("accident" ((ctgy . n)))
("acclimate" ((ctgy . v)))
("accommodate" ((ctgy . v)))
("acid" ((ctgy . n)))
("act" ((ctgy . n)) ((ctgy . v)))
("active" ((ctgy . adj)))
("adamant" ((ctgy . adj)))
("adapt" ((ctgy . v)))
("add" ((ctgy . v)))
("address" ((ctgy . v))
           ((ctgy . n)))
("adduce" ((ctgy . v)))
("adjudicate" ((ctgy . v)))
("adjust" ((ctgy . v)))
("admissible" ((ctgy . adj)))
("advent" ((ctgy . n)))
("advise" ((ctgy . v)))
("advocate" ((ctgy . n)) ((ctgy . v)))
("aerobic" ((ctgy . adj)))
("affable" ((ctgy . adj)))
("affected" ((ctgy . adj)))
("after" ((ctgy . adj))
   	 ((ctgy . prep)))
("air" ((ctgy . n)) ((ctgy . v)))
("Alaska" ((ctgy . n)))
("alcohol" ((ctgy . n)))
("ale" ((ctgy . n)))
("algebra" ((ctgy . n)))
("alien" ((ctgy . adj))
    ((ctgy . n)))
("all" ((ctgy . adj)) ((ctgy . pro)) ((ctgy . n)) ((ctgy . adv)))
("along" ((ctgy . prep)))
("allot" ((ctgy . v)))
("ambassador" ((ctgy . n)))
("ambitious" ((ctgy . adj)))
("American" ((ctgy . n)))
("anchor" ((ctgy . n)) ((ctgy . v)))
("anthology" ((ctgy . n)))
("apple" ((ctgy . n)))
("aqua" ((ctgy . n)))
("archaic" ((ctgy . adj)))
("archives" ((ctgy . n)))
("arm" ((ctgy . n)) ((ctgy . v)))
("as" ((ctgy . adv)) ((ctgy . prep)) ((ctgy . pro)))
("ash" ((ctgy . n)))
("at" ((ctgy . prep)))
("attend" ((ctgy . v)))
("authority" ((ctgy . n)))
("auto" ((ctgy . n)))
("avail" ((ctgy . n)) ((ctgy . v)))
("avarice" ((ctgy . n)))
("averse" ((ctgy . adj)))
("avoid" ((ctgy . v)))
("awe" ((ctgy . n)))
("axle" ((ctgy . n)))
("baby" ((ctgy . n)))
("back" ((ctgy . n))
  	 ((ctgy . adj))
  	 ((ctgy . adv)))
("bacon" ((ctgy . n)))
("bag" ((ctgy . n)) ((ctgy . v)))
("bake" ((ctgy . v)))
("bald" ((ctgy . adj)))
("ball" ((ctgy . n)))
("band" ((ctgy . n)))
("bankrupt" ((ctgy . n)))
("bar" ((ctgy . n)) ((ctgy . v)) ((ctgy . prep)))
("bare" ((ctgy . adj)))
("barmy" ((ctgy . adj)))
("base" ((ctgy . n)) ((ctgy . adj)))
("baseball" ((ctgy . n)))
("bath" ((ctgy . n)))
("battle" ((ctgy . n)) ((ctgy . v)))
("be" ((ctgy . v)))
("bead" ((ctgy . n)))
("bear" ((ctgy . n)) ((ctgy . v)))
("bed" ((ctgy . v)) ((ctgy . n)))
("bee" ((ctgy . n)))
("before" ((ctgy . adv)))
("behind" ((ctgy . adv)) ((ctgy . prep)))
("beg" ((ctgy . v)))
("bell" ((ctgy . n)))
("belly" ((ctgy . n)))
("berry" ((ctgy . n)))
("bestow" ((ctgy . v)))
("big" ((ctgy . adj))
       ((ctgy . adv)))
("bill" ((ctgy . n)))
("birth" ((ctgy . n)))
("black" ((ctgy . n))
         ((ctgy . adj)))
("blatant" ((ctgy . adj)))
("bleach" ((ctgy . n)) ((ctgy . v)))
("bleed" ((ctgy . v)))
("block" ((ctgy . n))
         ((ctgy . v)))
("blood" ((ctgy . n)))
("blow" ((ctgy . n)) ((ctgy . v)))
("blue" ((ctgy . n)) ((ctgy . adj)))
("boar" ((ctgy . n)))
("boat" ((ctgy . n)))
("body" ((ctgy . n)))
("bold" ((ctgy . n)))
("book" ((ctgy . n)))
("bore" ((ctgy . n))
        ((ctgy . v)))
("book" ((ctgy . n)) ((ctgy . v)))
("bump" ((ctgy . n)) ((ctgy . v)))
("bottle" ((ctgy . n)) ((ctgy . v)))
("butter" ((ctgy . n)) ((ctgy . v)))
("boulevard" ((ctgy . n)))
("boy" ((ctgy . n)))
("brass" ((ctgy . n)) ((ctgy . adj)))
("bread" ((ctgy . n)))
("breed" ((ctgy . n)) ((ctgy . v)))
("brick" ((ctgy . n)))
("bride" ((ctgy . n)))
("Brooklyn" ((ctgy . n)))
("broom" ((ctgy . n))
         ((ctgy . v)))
("brutal" ((ctgy . adj)))
("buck" ((ctgy . n)) ((ctgy . v)))
("bucket" ((ctgy . n)))
("bugle" ((ctgy . n)))
("bulb" ((ctgy . n)))
("bull" ((ctgy . n)) ((ctgy . adj)))
("burl" ((ctgy . n)))
("bush" ((ctgy . n)))
("butter" ((ctgy . n)) ((ctgy . v)))
("buzz" ((ctgy . n)) ((ctgy . v)))
("by" ((ctgy . prep))
      ((ctgy . adv)))
("cage" ((ctgy . n)))
("calf" ((ctgy . n)))
("calorie" ((ctgy . n)))
("camel" ((ctgy . n)))
("camp" ((ctgy . n)) ((ctgy . v)))
("candle" ((ctgy . n)))
("candy" ((ctgy . n)))
("cannon" ((ctgy . n)))
("cap" ((ctgy . n)) 
       ((ctgy . v)))
("capable" ((ctgy . adj)))
("caprice" ((ctgy . n)))
("captain" ((ctgy . n)))
("carditis" ((ctgy . n)))
("car" ((ctgy . n)))
("care" ((ctgy . n)))
("case" ((ctgy . n)))
("cat" ((ctgy . n)))
("celebate" ((ctgy . n)))
("celibate" ((ctgy . n)))
("cent" ((ctgy . n)))
("ceremony" ((ctgy . n)))
("chair" ((ctgy . n)))
("change" ((ctgy . v))
          ((ctgy . n)))
("cheese" ((ctgy . n)))
("child" ((ctgy . n)))
("chloride" ((ctgy . n)))
("choir" ((ctgy . n)) ((ctgy . v)))
("chuck" ((ctgy . n))
         ((ctgy . v)))
("church" ((ctgy . n)))
("city" ((ctgy . n)))
("civilize" ((ctgy . v)))
("classic" ((ctgy . n)))
("classify" ((ctgy . v)))
("clatter" ((ctgy . n)))
("claw" ((ctgy . n)) ((ctgy . v)))
("clay" ((ctgy . n)))
("cleft" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("clerk" ((ctgy . n)))
("cliff" ((ctgy . n)))
("clock" ((ctgy . n))
         ((ctgy . v)))
("clod" ((ctgy . n)))
("cloth" ((ctgy . n)))
("clothes" ((ctgy . n)))
("cloud" ((ctgy . n)) ((ctgy . v)))
("club" ((ctgy . v))((ctgy . n)))
("coal" ((ctgy . n)))
("cock" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("coerce" ((ctgy . v)))
("coffee" ((ctgy . n)))
("cognate" ((ctgy . adj)))
("consciene" ((ctgy . n)))
("coin" ((ctgy . n)))
("collar" ((ctgy . n)))
("collect" ((ctgy . n))
           ((ctgy . v)))
("commend" ((ctgy . v)))
("commune" ((ctgy . v)))
("compose" ((ctgy . adj)))
("comrade" ((ctgy . n)))
("concept" ((ctgy . n)))
("concession" ((ctgy . n)))
("conduct" ((ctgy . n)))
("confide" ((ctgy . v)))
("conjunct" ((ctgy . adj)))
("contempt" ((ctgy . n)))
("contingent" ((ctgy . n)))
("contract" ((ctgy . n))
            ((ctgy . v)))
("copper" ((ctgy . n)))
("cork" ((ctgy . n)))
("corn" ((ctgy . n)))
("correct" ((ctgy . v))
           ((ctgy . adj)))
("corse" ((ctgy . n)))
("costume" ((ctgy . n)))
("cotton" ((ctgy . n)) ((ctgy . adj)))
("couch" ((ctgy . n)))
("cough" ((ctgy . n)))
("council" ((ctgy . n)))
("count" ((ctgy . n)))
("counter" ((ctgy . n)) ((ctgy . adj)) ((ctgy . v)))
("country" ((ctgy . n))
           ((ctgy . adj)))
("cow" ((ctgy . n)))
("crack" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("cracker" ((ctgy . n)))
("cream" ((ctgy . n)) ((ctgy . v)))
("crook" ((ctgy . n)))
("cross" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("crow" ((ctgy . n)))
("crystal" ((ctgy . adj)))
("Cuba" ((ctgy . n)))
("curb" ((ctgy . n))
        ((ctgy . v)))
("cure" ((ctgy . v))
        ((ctgy . n)))
("cycle" ((ctgy . n)) ((ctgy . v)))
("cyst" ((ctgy . n)))
("danger" ((ctgy . n)))
("dark" ((ctgy . n))
   ((ctgy . adj)))
("dart" ((ctgy . n)))
("dead" ((ctgy . adv))
        ((ctgy . adj))
        ((ctgy . n)))
("dear" ((ctgy . n))
        ((ctgy . adj)))
("death" ((ctgy . n)))
("decent" ((ctgy . adj)))
("deer" ((ctgy . n)))
("define" ((ctgy . v)))
("defy" ((ctgy . v)))
("degrade" ((ctgy . v)))
("delegation" ((ctgy . n)))
("deliver" ((ctgy . v)))
("deluxe" ((ctgy . adj)))
("demoralize" ((ctgy . v)))
("dendrite" ((ctgy . n)))
("dendroid" ((ctgy . adj)))
("deodor" ((ctgy . n)))
("depend" ((ctgy . v)))
("desalinate" ((ctgy . v)))
("destruct" ((ctgy . n)))
("dew" ((ctgy . n)))
("dice" ((ctgy . n)))
("dill" ((ctgy . n)))
("dine" ((ctgy . v)))
("dish" ((ctgy . n)))
("dismiss" ((ctgy . v)))
("distill" ((ctgy . v)))
("divorce" ((ctgy . n)))
("doll" ((ctgy . n)))
("door" ((ctgy . n)))
("dose" ((ctgy . n)))
("double" ((ctgy . adj)) ((ctgy . n)) ((ctgy . v)) ((ctgy . adv)))
("doubt" ((ctgy . v))
         ((ctgy . n)))
("doze" ((ctgy . v)))
("drag" ((ctgy . n)) ((ctgy . v)))
("draw" ((ctgy . n)))
("dread" ((ctgy . adj)))
("dream" ((ctgy . n)) ((ctgy . v)))
("dress" ((ctgy . n)) ((ctgy . v)))
("drift" ((ctgy . n)) ((ctgy . v)))
("drip" ((ctgy . v)))
("drunk" ((ctgy . adj)))
("dry" ((ctgy . adj)))
("duck" ((ctgy . n)))
("dull" ((ctgy . adj)) ((ctgy . v)))
("dulls" ((ctgy . adj)))
("dune" ((ctgy . n)))
("duplicate" ((ctgy . n)) ((ctgy . adj)))
("durable" ((ctgy . adj)))
("early" ((ctgy . adj)))
("earth" ((ctgy . n)))
("east" ((ctgy . n)) ((ctgy . adj)))
("eat" ((ctgy . v)))
("edge" ((ctgy . v)))
("educate" ((ctgy . v))
           ((ctgy adj)))
("ege" ((ctgy . n)))
("elder" ((ctgy . n)))
("electron" ((ctgy . n)))
("elevate" ((ctgy . v)))
("end" ((ctgy . n))
       ((ctgy . v)))
("engine" ((ctgy . n)))
("ensile" ((ctgy . v)))
("enter" ((ctgy . v)))
("epiglottis" ((ctgy . n)))
("eradicate" ((ctgy . v)))
("erase" ((ctgy . v)))
("escape" ((ctgy . adj))          ((ctgy . n))
          ((ctgy . v)))
("estuary" ((ctgy . n)))
("even" ((ctgy . adj)) ((ctgy . adv)) ((ctgy . v)))
("event" ((ctgy . n)))
("exorbitant" ((ctgy . adj)))
("expectant" ((ctgy . adj)))
("expede" ((ctgy . v)))
("extravagant" ((ctgy . adj)))
("exultant" ((ctgy . adj)))
("eye" ((ctgy . n)))
("fable" ((ctgy . n)))
("face" ((ctgy . n)))
("fact" ((ctgy . n)))
("fair" ((ctgy . n)) ((ctgy . adj)))
("farce" ((ctgy . n)))
("farm" ((ctgy . v)) ((ctgy . n)))
("fast" ((ctgy . adv)) ((ctgy . adj)))
("fat" ((ctgy . n))
       ((ctgy . adj)))
("feasible" ((ctgy . adj)))
("feather" ((ctgy . n)))
("fever" ((ctgy . n)))
("fiction" ((ctgy . n)))
("field" ((ctgy . n))
         ((ctgy . adj)))
("finance" ((ctgy . n))
           ((ctgy . v)))
("finger" ((ctgy . n)) ((ctgy . v)))
("fire" ((ctgy . v)) ((ctgy . n)))
("fish" ((ctgy . n)))
("fist" ((ctgy . n)))
("flag" ((ctgy . n)))
("flap" ((ctgy . n)))
("flat" ((ctgy . adj))
        ((ctgy . adv)))
("flax" ((ctgy . n)))
("flea" ((ctgy . n)))
("fleece" ((ctgy . n))
          ((ctgy . v)))
("flex" ((ctgy . v)))
("flood" ((ctgy . n)) ((ctgy . v)))
("fluff" ((ctgy . n)))
("folk" ((ctgy . n))
        ((ctgy . adj)))
("foot" ((ctgy . v)) ((ctgy . n)))
("for" ((ctgy . prep)))
("fore" ((ctgy . n)) ((ctgy . prep)) ((ctgy . adj)))
("foremast" ((ctgy . n)))
("form" ((ctgy . v)))
("forth" ((ctgy . adv)))
("four" ((ctgy . n)))
("free" ((ctgy . adj)) ((ctgy . n)))
("french" ((ctgy . n)))
("frog" ((ctgy . n)))
("frost" ((ctgy . n)) ((ctgy . v)))
("fry" ((ctgy . v)))
("fudge" ((ctgy . n)))
("gab" ((ctgy . v)))
("games" ((ctgy . v)))
("garlic" ((ctgy . n)))
("gas" ((ctgy . n)))
("gate" ((ctgy . n)))
("geld" ((ctgy . n)))
("gentleman" ((ctgy . n)) ((ctgy . adj)))
("green" ((ctgy . n)) ((ctgy . adj)))
("gymnast" ((ctgy . n)))
("gynecology" ((ctgy . n)))
("germ" ((ctgy . n)))
("girl" ((ctgy . n)))
("glass" ((ctgy . n)))
("globule" ((ctgy . n)))
("glue" ((ctgy . n)) ((ctgy . v)))
("gold" ((ctgy . adj)) ((ctgy . n)))
("gondola" ((ctgy . n)))
("good" ((ctgy . n)) ((ctgy . adj)))
("goose" ((ctgy . n)))
("grace" ((ctgy . n))
         ((ctgy . v)))
("grand" ((ctgy . n))
    	 ((ctgy . adj)))
("grave" ((ctgy . n)))
("green" ((ctgy . n))
         ((ctgy . adj)))
("grocer" ((ctgy . n)))
("grub" ((ctgy . n)) ((ctgy . v)))
("gutter" ((ctgy . n)))
("hair" ((ctgy . n)))
("half" ((ctgy . n)) ((ctgy . adj)))
("hand" ((ctgy . n)))
("handy" ((ctgy . adj)))
("hard" ((ctgy . adj)))
("hare" ((ctgy . n)))
("harvest" ((ctgy . n)))
("hat" ((ctgy . n)))
("hatch" ((ctgy . n))
         ((ctgy . v)))
("hatchet" ((ctgy . n)))
("hate" ((ctgy . n)) ((ctgy . v)))
("head" ((ctgy . v))
	((ctgy . n))
        ((ctgy . adj)))
("heart" ((ctgy . n)))
("heat" ((ctgy . n))
        ((ctgy . v)))
("height" ((ctgy . n)))
("heir" ((ctgy . n)))
("hell" ((ctgy . n)))
("help" ((ctgy . n)(num . sing))
        ((ctgy . v)))
("hen" ((ctgy . n)))
("herb" ((ctgy . n)))
("hereto" ((ctgy . adv)))
("hero" ((ctgy . n)))
("hicks" ((ctgy . n))((ctgy . adj)))
("high" ((ctgy . n)) ((ctgy . adj)))
("hill" ((ctgy . n))
        ((ctgy . v)))
("hind" ((ctgy . n))
        ((ctgy . adj)))
("hobby" ((ctgy . n)))
("hog" ((ctgy . n)))
("home" ((ctgy . adj)) ((ctgy . n)))
("honey" ((ctgy . n)) ((ctgy . adj)))
("hood" ((ctgy . n)))
("hook" ((ctgy . n)) ((ctgy . v)))
("hop" ((ctgy . n)) ((ctgy . v)))
("horse" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("horeseman" ((ctgy . n)))
("host" ((ctgy . n)))
("hour" ((ctgy . n)))
("house" ((ctgy . n)) ((ctgy . v)))
("humor" ((ctgy . n)) ((ctgy . v)))
("ice" ((ctgy . n)))
("ideal" ((ctgy . n))
         ((ctgy . adj)))
("implicate" ((ctgy . v)))
("implicit" ((ctgy . adj)))
("improbable" ((ctgy . adj)))
("in" ((ctgy . prep)) ((ctgy . adv)) ((ctgy . adj)) ((ctgy . n)))
("inch" ((ctgy . n)))
("infuse" ((ctgy . v)))
("inherit" ((ctgy . v)))
("initial" ((ctgy . n))
           ((ctgy . adj)))
("initiate" ((ctgy .n))
            ((ctgy . v)))
("inject" ((ctgy . v)))
("insomnia" ((ctgy . n)))
("intoxicate" ((ctgy . v)))
("invest" ((ctgy . v)))
("irk" ((ctgy . v)) ((ctgy . n)))
("iron" ((ctgy . v)) ((ctgy . n)))
("jab" ((ctgy . v)))
("jack" ((ctgy . n)) ((ctgy . v)))
("Japan" ((ctgy . n)))
("jasmine" ((ctgy . n)))
("jest" ((ctgy . v)))
("job" ((ctgy . n)))
("jock" ((ctgy . n)))
("jog" ((ctgy . v)))
("join" ((ctgy . v)))
("joke" ((ctgy . n)) ((ctgy . v)))
("journal" ((ctgy . n)))
("joy" ((ctgy . n))
       ((ctgy . v)))
("Judaic" ((ctgy . adj)))
("judge" ((ctgy . n))
         ((ctgy . v)))
("judgement" ((ctgy . n)))
("judicative" ((ctgy . adj)))
("judicial" ((ctgy . adj)))
("juice" ((ctgy . n)))
("June" ((ctgy . n)))
("knife" ((ctgy . n)))
("kind" ((ctgy . n)) ((ctgy . adj)))
("king" ((ctgy . n)))
("labor" ((ctgy . n))
         ((ctgy . v)))
("lack" ((ctgy . n)) ((ctgy . v)))
("lake" ((ctgy . n)))
("land" ((ctgy . v)) ((ctgy . n)))
("latent" ((ctgy . adj)))
("laugh" ((ctgy . v)))
("lead" ((ctgy . n)))
("lease" ((ctgy . n)) ((ctgy . v)))
("leather" ((ctgy . n)))
("lecher" ((ctgy . n)))
("left" ((ctgy . n))
        ((ctgy . adj))
        ((ctgy . adv)))
("leg" ((ctgy . n)))
("legend" ((ctgy . n)))
("legislate" ((ctgy . v)))
("lemon" ((ctgy . n)))
("length" ((ctgy . n)))
("lie" ((ctgy . v)))
("life" ((ctgy . n)))
("light" ((ctgy . n)))
("like" ((ctgy . adj))
        ((ctgy . prep))
        ((ctgy . n))
        ((ctgy . adv))
        ((ctgy . v)))
("line" ((ctgy . n)))
("lip" ((ctgy . n))
       ((ctgy . adj)))
("loan" ((ctgy . n)))
("lock" ((ctgy . n)) ((ctgy . v)))
("loco" ((ctgy . n)) ((ctgy . adj)))
("loin" ((ctgy . n)))
("lone" ((ctgy . adj)))
("long" ((ctgy . adj))
        ((ctgy . n))
        ((ctgy . adv))
        ((ctgy . v)))
("lord" ((ctgy . n)))
("love" ((ctgy . n)))
("lubricate" ((ctgy . v)))
("luck" ((ctgy . n)))
("lumber" ((ctgy . n)))
("Luther" ((ctgy . n)))
("madonna" ((ctgy . adj))
           ((ctgy . n)))
("magnific" ((ctgy . adj)))
("mail" ((ctgy . n)))
("main" ((ctgy . n))
        ((ctgy . adj)))
("major" ((ctgy . n))
         ((ctgy . adj)))
("mammal" ((ctgy . n)))
("man" ((ctgy . adj)) ((ctgy . n)))
("manage" ((ctgy . n))
          ((ctgy . v)))
("manager" ((ctgy . n)))
("mania" ((ctgy . n)))
("marksman" ((ctgy . n)))
("match" ((ctgy . n))
         ((ctgy . v)))
("mean" ((ctgy . n)) ((ctgy . adj)))
("medic" ((ctgy . n)))
("mediate" ((ctgy . v)))
("Mendel" ((ctgy . n)))
("method" ((ctgy . n)))
("middle" ((ctgy . n)) ((ctgy . adj)))
("migrate" ((ctgy . v)))
("militant" ((ctgy . adj)))
("mill" ((ctgy . n)) ((ctgy . v)))
("million" ((ctgy . n)))
("miss" ((ctgy . v)))
("mist" ((ctgy . n)))
("mix" ((ctgy . v)))
("mob" ((ctgy . n)))
("mole" ((ctgy . n)))
("money" ((ctgy . n)))
("moon" ((ctgy . n)) ((ctgy . v)))
("motor" ((ctgy . n)) ((ctgy . adj)))
("mouse" ((ctgy . n)))
("mountain" ((ctgy . n)) ((ctgy . adj)))
("mouth" ((ctgy . n)))
("movie" ((ctgy . n)))
("mud" ((ctgy . n)))
("multiplicate" ((ctgy . adj)))
("mummy" ((ctgy . n)))
("munificent" ((ctgy . adj)))
("munition" ((ctgy . n)))
("neb" ((ctgy . n)))
("neck" ((ctgy . n))
        ((ctgy . v)))
("needle" ((ctgy . n)) ((ctgy . v)))
("nerve" ((ctgy . n)))
("news" ((ctgy . n)))
("nice" ((ctgy . adj)))
("night" ((ctgy . n)) ((ctgy . adj)))
("nip" ((ctgy . v)) ((ctgy . n)))
("nomadic" ((ctgy . adj)))
("noon" ((ctgy . n)) ((ctgy . adj)))
("note" ((ctgy . n)))
("null" ((ctgy . adj))
        ((ctgy . n)))
("nurse" ((ctgy . n)) ((ctgy . v)))
("nut" ((ctgy . n)))
("oak" ((ctgy . n)))
("odor" ((ctgy . n)))
("of" ((ctgy . prep)))
("off" ((ctgy . adv)) ((ctgy . adj)) ((ctgy . prep)))
("office" ((ctgy . n)))
("official" ((ctgy . n)))
("often" ((ctgy . adv)))
("old" ((ctgy . n))
       ((ctgy . adj)))
("onto" ((ctgy . prep)))
("opaque" ((ctgy . adj)))
("opera" ((ctgy . n)))
("operate" ((ctgy . v)))
("oppose" ((ctgy . adj)))
("orange" ((ctgy . n)) ((ctgy . adj)))
("out" ((ctgy . adv))
       ((ctgy . adj))
       ((ctgy . prep))
       ((ctgy . v))
       ((ctgy . n)))
("over" ((ctgy . adv))
        ((ctgy . n))
        ((ctgy . prep))
        ((ctgy . adj)))
("ox" ((ctgy . n)))
("oyster" ((ctgy . n)))
("pack" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("paint" ((ctgy . n)))
("pan" ((ctgy . v)) ((ctgy . n)))
("pancreas" ((ctgy . n)))
("pantheism" ((ctgy . n)))
("parodist" ((ctgy . n)))
("paste" ((ctgy . n)))
("path" ((ctgy . n)))
("patriot" ((ctgy . n)))
("pen" ((ctgy . n)))
("percent" ((ctgy . adv)))
("percept" ((ctgy . n)))
("perfect" ((ctgy . n)))
("perfume" ((ctgy . n))
           ((ctgy . v)))
("perish" ((ctgy . v)))
("person" ((ctgy . n)))
("personate" ((ctgy . v)))
("perspire" ((ctgy . v)))
("pharmacy" ((ctgy . n)))
("phlebitis" ((ctgy . n)))
("phobia" ((ctgy . n)))
("physics" ((ctgy . n)))
("piano" ((ctgy . n)))
("picture" ((ctgy . n)))
("pie" ((ctgy . n)))
("piece" ((ctgy . n)))
("pig" ((ctgy . n)))
("pigeon" ((ctgy . n)))
("pink" ((ctgy . adj))
        ((ctgy . n)))
("pipe" ((ctgy . n)) ((ctgy . v)))
("pitch" ((ctgy . n)))
("pity" ((ctgy . n))
        ((ctgy . v)))
("play" ((ctgy . v))
        ((ctgy . n)))
("please" ((ctgy . v)))
("poet" ((ctgy . n)))
("pole" ((ctgy . n)))
("politic" ((ctgy . adj)))
("poop" ((ctgy . n)))
("pop" ((ctgy . v))((ctgy . n)) ((ctgy . adj)))
("pose" ((ctgy . v)))
("pound" ((ctgy . n)))
("praise" ((ctgy . n))
          ((ctgy . v)))
("prat" ((ctgy . n)))
("predicate" ((ctgy . v)))
("prefect" ((ctgy . n)))
("prime" ((ctgy . adj)) ((ctgy . n)))
("prince" ((ctgy . n)))
("produce" ((ctgy . v)))
("prosthesis" ((ctgy . n)))
("protein" ((ctgy . n)))
("prove" ((ctgy . v)))
("psalm" ((ctgy . n)))
("public" ((ctgy . adj))
          ((ctgy . n)))
("pure" ((ctgy . adj)))
("purge" ((ctgy . v)))
("pussy" ((ctgy . n)) ((ctgy . adj)))
("quick" ((ctgy . adj)))
("race" ((ctgy . n))
        ((ctgy . v)))
("rag" ((ctgy . n)))
("ransom" ((ctgy . n)))
("rare" ((ctgy . adj)))
("rattle" ((ctgy . n)) ((ctgy . v)))
("rain" ((ctgy . n)) ((ctgy . v)))
("razor" ((ctgy . n)))
("read" ((ctgy . v)))
("rearm" ((ctgy . v)))
("red" ((ctgy . n))
       ((ctgy . adj)))
("reduce" ((ctgy . v)))
("remote" ((ctgy . adj)))
("resemble" ((ctgy . v)))
("reside" ((ctgy . v)))
("response" ((ctgy . n)))
("retard" ((ctgy . n))
          ((ctgy . v)))
("revise" ((ctgy . v)))
("rick" ((ctgy . n)))
("rid" ((ctgy . v)))
("ridge" ((ctgy . n)))
("rip" ((ctgy . n)) ((ctgy . v)))
("rise" ((ctgy . v)) ((ctgy . n)))
("river" ((ctgy . n)))
("rob" ((ctgy . v)))
("rock" ((ctgy . n)) ((ctgy . v)))
("roof" ((ctgy . n)))
("rope" ((ctgy . n)) ((ctgy . v)))
("rose" ((ctgy . n)) ((ctgy . adj)))
("rough" ((ctgy . n)) ((ctgy . adj)) ((ctgy . v)))
("round" ((ctgy . v))
	 ((ctgy . prep))
	 ((ctgy . n))
         ((ctgy . adj)))
("run" ((ctgy . n))
       ((ctgy . v)))
("saddle" ((ctgy . n)) ((ctgy . v)))
("safe" ((ctgy . n)) ((ctgy . adj)))
("sail" ((ctgy . n)))
("sale" ((ctgy . n)))
("sand" ((ctgy . n)))
("sauce" ((ctgy . n)))
("school" ((ctgy . n)))
("score" ((ctgy . n)))
("scrub" ((ctgy . n)) ((ctgy . v)))
("sea" ((ctgy . n)))
("second" ((ctgy . n))
          ((ctgy . adj)))
("seed" ((ctgy . n)))
("select" ((ctgy . v)))
("seam" ((ctgy . n)))
("sense" ((ctgy . v)))
("sermon" ((ctgy . n)))
("sexual" ((ctgy . n)))
("shag" ((ctgy . n)))
("sheep" ((ctgy . n)))
("sharp" ((ctgy . n))
         ((ctgy . adj)))
("sheep" ((ctgy . n)))
("ship" ((ctgy . n)) ((ctgy . v)))
("shirt" ((ctgy . n)))
("shoe" ((ctgy . n)))
("shop" ((ctgy . n)))
("sick" ((ctgy . adj)))
("side" ((ctgy . adj)) ((ctgy . n)))
("sign" ((ctgy . n)))
("silver" ((ctgy . n)))
("sing" ((ctgy . v)))
("sink" ((ctgy . n)))
("skin" ((ctgy . n))
        ((ctgy . v)))
("sleeps" ((ctgy . v)))
("slice" ((ctgy . v)))
("slug" ((ctgy . n))
        ((ctgy . v)))
("slumber" ((ctgy . n))
           ((ctgy . v)))
("smear" ((ctgy . v))
         ((ctgy . n)))
("smock" ((ctgy . n)))
("smooth" ((ctgy . v)) ((ctgy . adj)))
("snip" ((ctgy . n)))
("snob" ((ctgy . n)))
("snow" ((ctgy . v)) ((ctgy . n)))
("snub" ((ctgy . n))
        ((ctgy . v)))
("soap" ((ctgy . n)))
("song" ((ctgy . n)))
("soon" ((ctgy . adv)))
("squares" ((ctgy . n)) ((ctgy . adj)))
("space" ((ctgy . n)))
("spell" ((ctgy . v)))
("spend" ((ctgy . v)))
("splay" ((ctgy . n)) ((ctgy. v)) ((ctgy . adj)))
("spring" ((ctgy . n)) ((ctgy . v)) ((ctgy . adj)))
("stable" ((ctgy . n)))
("stage" ((ctgy . n)) ((ctgy . v)))
("state" ((ctgy . n)))
("statue" ((ctgy . n)))
("steep" ((ctgy . adj)))
("step" ((ctgy . n)) ((ctgy . v)))
("stern" ((ctgy . n)) ((ctgy . adj)))
("steward" ((ctgy . n)))
("stoke" ((ctgy . v)))
("stone" ((ctgy . v)) ((ctgy . n)) ((ctgy . adj)))
("stop" ((ctgy . v))
        ((ctgy . n)))
("strength" ((ctgy . n)))
("stride" ((ctgy . n)))
("strong" ((ctgy . adj)))
("stud" ((ctgy . n)))
("stun" ((ctgy . n)) ((ctgy . v)))
("style" ((ctgy . n)))
("submissive" ((ctgy . adj)))
("success" ((ctgy . n)))
("suck" ((ctgy . n)) ((ctgy . v)))
("sugar" ((ctgy . n))
         ((ctgy . adj)))
("sulfur" ((ctgy . n)))
("summer" ((ctgy . n)) ((ctgy . adj)))
("sun" ((ctgy . v)) ((ctgy . n)))
("super" ((ctgy . n)) ((ctgy . adj)))
("superintendent" ((ctgy . n)))
("supper" ((ctgy . n)))
("suspicious" ((ctgy . adj)))
("sweep" ((ctgy . n)) ((ctgy . v)))
("sweet" ((ctgy . adj)))
("swivel" ((ctgy . n)) ((ctgy . v)))
("swine" ((ctgy . n)))
("sword" ((ctgy . n)))
("table" ((ctgy . n)))
("tact" ((ctgy . n)))
("tail" ((ctgy . n))
        ((ctgy . adj))
        ((ctgy . v)))
("take" ((ctgy . v)))
("taste" ((ctgy . n))
         ((ctgy . v)))
("tea" ((ctgy . n)))
("teacher" ((ctgy . n)))
("team" ((ctgy . n))
        ((ctgy . v)))
("television" ((ctgy . n)))
("terrace" ((ctgy . n)))
("theory" ((ctgy . n)))
("thorough" ((ctgy . adj)))
("tickle" ((ctgy . n)) ((ctgy . v)))
("tide" ((ctgy . n)))
("tie" ((ctgy . n)) ((ctgy . v)))
("tile" ((ctgy . n)))
("time" ((ctgy . n))
        ((ctgy . v))
        ((ctgy . adj)))
("tin" ((ctgy . n)))
("toga" ((ctgy . n)))
("tomb" ((ctgy . n)))
("toss" ((ctgy . n)) ((ctgy . v)))
("tourney" ((ctgy . n))
           ((ctgy . v)))
("tow" ((ctgy . n)) ((ctgy . v)))
("town" ((ctgy . n)))
("trek" ((ctgy . n)) ((ctgy . v)))
("tribe" ((ctgy . n)))
("trim" ((ctgy . v)))
("try" ((ctgy . v)))
("tune" ((ctgy . n)) ((ctgy . v)))
("Tunis" ((ctgy . n)))
("turkey" ((ctgy . n)))
("under" ((ctgy . prep))
         ((ctgy . adv))
         ((ctgy . adj)))
("up" ((ctgy . n))
      ((ctgy . adj))
      ((ctgy . adv)))
("use" ((ctgy . v)))
("usher" ((ctgy . n)))
("utter" ((ctgy . v))
         ((ctgy . adj)))
("vagrant" ((ctgy . n)))
("valve" ((ctgy . n)))
("vampire" ((ctgy . n)))
("vaporize" ((ctgy . v)))
("veracious" ((ctgy . adj)))
("verb" ((ctgy . n)))
("verse" ((ctgy . n)))
("vice" ((ctgy . adj)) ((ctgy . n)))
("villein" ((ctgy . n)))
("vociferate" ((ctgy . v)))
("vociferous" ((ctgy . adj)))
("wain" ((ctgy . n)))
("waist" ((ctgy . n)))
("walk" ((ctgy . v)))
("wall" ((ctgy . v)) ((ctgy . n)))
("want" ((ctgy . n))
        ((ctgy . v)))
("warehouse" ((ctgy . n)))
("warm" ((ctgy . adj)) ((ctgy . v)))
("wash" ((ctgy . adj))
        ((ctgy . n))
        ((ctgy . v)))
("washer" ((ctgy . n)))
("waste" ((ctgy . adj)))
("watch" ((ctgy . n))
         ((ctgy . v)))
("water" ((ctgy . v)) ((ctgy . n)))
("way" ((ctgy . n)))
("weak" ((ctgy . adj)))
("weep" ((ctgy . v)))
("weigh" ((ctgy . n)))
("whet" ((ctgy . v))
        ((ctgy . n)))
("white" ((ctgy . adj)))
("wide" ((ctgy . adj)) ((ctgy . adv)))
("widow" ((ctgy . n)))
("wife" ((ctgy . n)))
("wild" ((ctgy . n)) ((ctgy . adj)))
("wind" ((ctgy . v))
        ((ctgy . n)))
("winter" ((ctgy . v)) ((ctgy . n)) ((ctgy . adj)))
("with" ((ctgy . prep)))
("whip" ((ctgy . n)) ((ctgy . v)))
("whirl" ((ctgy . n)) ((ctgy . v)))
("white" ((ctgy . n)) ((ctgy . adj)))
("wood" ((ctgy . n))
        ((ctgy . adj))
        ((ctgy . v)))
("work" ((ctgy . n)))
("would" ((ctgy . v)))
("wrist" ((ctgy . n)))
("year" ((ctgy . n)))
("Yiddish" ((ctgy . n)))
("youth" ((ctgy . n)))("calf" ((ctgy . n)))
("loaf" ((ctgy . n)))
("thief" ((ctgy . n)))
